export const movieCategory1 = {
  titleBar: "Popular on Netflix",
  moviesDetailes: [
    {
      id: "A1",
      images: "/photo/img1.jpg",
      title: "Saaho",
      information: `2 ${"h"} 45 ${"m"}`,
      agee: `${"U/A"} ${"16+"}`,
      sal: 2017,
      genre: "Action",
      describ:
        "To avenge his father's death, a young man leads an army into battle against a cruel tyrant in this Hindi conclusion .",
      casting: "Starring:  Prabhas,Rana Daggubati,Anushka Shetty",
    },
    {
      id: "A2",
      images: "/photo/img2.jpg",
      title: "RRR (Hindi)",
      information: ` 2${"h"}  51${"m"}`,
      agee: `${"U/A"} ${"16+"}`,
      sal: 2019,
      genre: "Action",
      describ:
        "In a fictional megalopolis, a stunning underworld theft triggers a fierce power struggle among the gangsters, with an enigmatic cop on their trail.",
      casting: "Starring:  Prabhas,Shraddha Kapoor,Jackie Shroff",
    },
    {
      id: "A3",
      images: "/photo/img3.jpg",
      title: "OMG 2",
      information: ` 2${"h"} 16 ${"m"}`,
      agee: `${"U/A"} ${"17+"}`,
      sal: 2016,
      genre: "love",
      describ:
        "A martial artist faces his biggest test when he has to travel to Bangkok to rescue the woman he loves from the clutches of his romantic rival. ",
      casting: "Starring:  Tiger Shroff,Shraddha Kapoor,Sudheer Babu",
    },
    {
      id: "A4",
      images: "/photo/img4.jpg",
      title: "Mission Raniganj",
      information: ` 2${"h"}  53${"m"}`,
      agee: `${"U/A"} ${"1+"}`,
      sal: 2012,
      genre: "Action",
      describ:
        "After witnessing the murder of his upstanding father, a village boy moves to Mumbai and falls into a life of crime with a singular motive: revenge.",
      casting: "Starring:  Hrithik Roshan,Rishi Kapoor,Sanjay Dutt",
    },
    {
      id: "A5",
      images: "/photo/img5.jpg",
      title: "Baahubali 2: The Conclusion (Hindi)",
      // "The Mysterious Island",
      information: `2 ${"h"} 30 ${"m"}`,
      agee: `${"U/A"} ${"15+"}`,
      sal: 2024,
      genre: "Adventure",
      describ:
        "A group of explorers crash-land on an uncharted island and discover its hidden secrets, including mythical creatures and ancient mysteries.",
      casting: "Starring: Chris Hemsworth, Scarlett Johansson, Tom Holland",
    },
    {
      id: "A6",
      images: "/photo/img6.jpg",
      title: "LEO (Tamil)",
      information: `2 ${"h"} 05 ${"m"}`,
      agee: `${"U/A"} ${"12+"}`,
      sal: 2025,
      genre: "Science Fiction",
      describ:
        "A team of intergalactic heroes must unite to stop a powerful villain from destroying the galaxy and unraveling the fabric  time.",
      casting: "Starring: Zoe Saldana, Chris Pratt, Vin Diesel",
    },
    {
      id: "A7",
      images: "/photo/img7.jpg",
      title: "Jawan: Extended Cut",
      information: `1 ${"h"} 55 ${"m"}`,
      agee: `${"U"} ${"10+"}`,
      sal: 2022,
      genre: "Romance",
      describ:
        "Two souls destined to be together find love across lifetimes, facing challenges that test the strength of their connection and the power of eternal love.",
      casting: "Starring: Zendaya, Timothée Chalamet, Emma Watson",
    },
    {
      id: "A8",
      images: "/photo/img8.jpg",
      title: "HUNTER",
      information: `2${"h"} 28${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2010,
      genre: "Sci-Fi",
      describ:
        "A skilled thief who enters people's dreams to steal their deepest secrets is tasked with planting an idea into someone's mind.",
      casting: "Starring: Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
    },
    {
      id: "A9",
      images: "/photo/img9.jpg",
      title: "Mission Majnu",
      information: `2${"h"} 32${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2008,
      genre: "Action",
      describ:
        "Batman faces the Joker, a criminal mastermind with a twisted sense of humor, in a battle to save Gotham City from destruction.",
      casting: "Starring: Christian Bale, Heath Ledger, Aaron Eckhart",
    },

    {
      id: "A10",
      images: "/photo/img10.jpg",
      title: "The Silence of the Lambs",
      information: `1${"h"} 58${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1991,
      genre: "Thriller",
      describ:
        "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
      casting: "Starring: Jodie Foster, Anthony Hopkins, Lawrence A. Bonney",
    },
    {
      id: "A11",
      images: "/photo/img11.jpg",
      title: "Baagi 2",
      information: `2${"h"} 35${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 2000,
      genre: "Action",
      describ:
        "A betrayed Roman general seeks justice for his family and revenge against the corrupt emperor who murdered his family and sent him into slavery.",
      casting: "Starring: Russell Crowe, Joaquin Phoenix, Connie Nielsen",
    },
  ],
};

export const movieCategory2 = {
  titleBar: "Bollywood Movies",
  moviesDetailes: [
    {
      id: "B1",
      images: "/photo/img12.jpg",
      title: "Agneepath (2012)",
      information: `2 ${"h"} 25 ${"m"}`,
      agee: `${"U/A"} ${"14+"}`,
      sal: 2022,
      genre: "Adventure",
      describ:
        "An archaeologist discovers a hidden city in the jungle and must navigate traps, puzzles, and rival treasure hunters to uncover its secrets.",
      casting: "Starring: Sandra Bullock, Channing Tatum, Daniel Radcliffe",
    },
    {
      id: "B2",
      images: "/photo/img13.jpg",
      title: "Triple Frontier",
      information: `2 ${"h"} 10 ${"m"}`,
      agee: `${"U"} ${"10+"}`,
      sal: 2023,
      genre: "Science Fiction",
      describ:
        "A space mission to a distant galaxy goes awry, leading the crew to face extraterrestrial challenges and uncover the mysteries of the cosmos.",
      casting: "Starring: Ryan Gosling, Emma Stone, Michael Fassbender",
    },
    {
      id: "B3",
      images: "/photo/img14.jpg",
      title: "Escape Plan",
      information: `1 ${"h"} 50 ${"m"}`,
      agee: `${"U"} ${"12+"}`,
      sal: 2021,
      genre: "Romance",
      describ:
        "In a small town, a chance encounter brings together two people from different eras, sparking a timeless romance that transcends the boundaries of time.",
      casting: "Starring: Jennifer Lawrence, Chris Evans, Emily Blunt",
    },
    {
      id: "B4",
      images: "/photo/img15.jpg",
      title: "Love Today",
      information: `2 ${"h"} 30 ${"m"}`,
      agee: `${"U/A"} ${"15+"}`,
      sal: 2022,
      genre: "Love",
      describ:
        "A detective delves into a series of mysterious disappearances in a city plagued by shadows, uncovering dark secrets that threaten to consume the entire population.",
      casting:
        "Starring: Benedict Cumberbatch, Natalie Portman, Jake Gyllenhaal",
    },

    {
      id: "B5",
      images: "/photo/img16.jpg",
      title: "Interstellar",
      information: `2${"h"} 49${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2014,
      genre: "Sci-Fi",
      describ:
        "A group of explorers embarks on a space journey through a wormhole in search of a new habitable planet for humanity.",
      casting: "Starring: Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    },
    {
      id: "B6",
      images: "/photo/img17.jpg",
      title: "The Shawshank Redemption",
      information: `2${"h"} 22${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1994,
      genre: "Drama",
      describ:
        "Two imprisoned men form a bond over several years, finding solace and eventual redemption through acts of common decency.",
      casting: "Starring: Tim Robbins, Morgan Freeman, Bob Gunton",
    },
    {
      id: "B7",
      images: "/photo/img18.jpg",
      title: "Avatar",
      information: `2${"h"} 42${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2009,
      genre: "Action",
      describ:
        "A paraplegic marine is dispatched to the moon Pandora on a unique mission and becomes torn between following orders and protecting an alien civilization.",
      casting: "Starring: Sam Worthington, Zoe Saldana, Sigourney Weaver",
    },
    {
      id: "B8",
      images: "/photo/img19.jpg",
      title: "Forrest Gump",
      information: `2${"h"} 22${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 1994,
      genre: "Drama",
      describ:
        "The life journey of a man with a low IQ who witnesses and unwittingly influences several defining historical events in the 20th century USA.",
      casting: "Starring: Tom Hanks, Robin Wright, Gary Sinise",
    },
    {
      id: "B9",
      images: "/photo/img20.jpg",
      title: "The Matrix",
      information: `2${"h"} 16${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1999,
      genre: "Sci-Fi",
      describ:
        "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      casting: "Starring: Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    },
    {
      id: "B10",
      images: "/photo/img21.jpg",
      title: "Pulp Fiction",
      information: `2${"h"} 34${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1994,
      genre: "Crime",
      describ:
        "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      casting: "Starring: John Travolta, Uma Thurman, Samuel L. Jackson",
    },
    {
      id: "B11",
      images: "/photo/img22.jpg",
      title: "The Godfather",
      information: `2${"h"} 55${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1972,
      genre: "Crime",
      describ:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      casting: "Starring: Marlon Brando, Al Pacino, James Caan",
    },
  ],
};

export const movieCategory3 = {
  titleBar: "Hollywood Movies",
  moviesDetailes: [
    {
      id: "C1",
      images: "/photo/img23.jpg",
      title: "Yu Yu Hakusho",
      information: `1 ${"h"} 41 ${"m"}`,
      agee: `${"U/A"} ${"13+"}`,
      sal: 2023,
      genre: "Action",
      describ:
        "After a selfless act costs him his life, teen delinquent Yusuke Urameshi is chosen as a Spirit Detective to investigate cases involving rogue yokai.",
      casting: "Starring:  Takumi Kitamura,Jun Shison,Kanata Hongo",
    },
    {
      id: "C2",
      images: "/photo/img24.jpg",
      title: "Hunter X Hunter (2011)",
      information: `3 ${"h"} 17 ${"m"}`,
      agee: `${"U/A"} ${"12+"}`,
      sal: 2011,
      genre: "Drama",
      describ:
        "To fulfill his dreams of becoming a legendary Hunter like his dad, a young boy must pass a rigorous examination and find his missing father.",
      casting: "Starring:  Megumi Han,Mariya Ise,Keiji Fujiwara",
    },
    {
      id: "C3",
      images: "/photo/img25.jpg",
      title: "Mission Majnu",
      information: `2 ${"h"} 9 ${"m"}`,
      agee: `${"U/A"} ${"16+"}`,
      sal: 2023,
      genre: "Action",
      describ:
        "In the 1970s, an undercover Indian spy takes on a deadly mission to expose a covert nuclear weapons program in the heart of Pakistan.",
      casting: "Starring: Sidharth Malhotra,Rashmika Mandanna,Parmeet Sethi",
    },
    {
      id: "C4",
      images: "/photo/img26.jpg",
      title: "dfgh",
      information: `3 ${"h"}  05${"m"}`,
      agee: `${"U/A"} ${"16+"}`,
      sal: 2022,
      genre: "Action",
      describ:
        "A fearless warrior on a perilous mission comes face to face with a steely cop serving British forces in this epic saga set in pre-independent India.",
      casting: "Starring:  NTR Jr.,Ram Charan,Ajay Devgn",
    },
    {
      id: "C5",
      images: "/photo/img27.jpg",
      title: "Interstellar",
      information: `2${"h"} 49${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2014,
      genre: "Sci-Fi",
      describ:
        "A group of explorers embarks on a space journey through a wormhole in search of a new habitable planet for humanity.",
      casting: "Starring: Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    },
    {
      id: "C6",
      images: "/photo/img28.jpg",
      title: "The Shawshank Redemption",
      information: `2${"h"} 22${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1994,
      genre: "Drama",
      describ:
        "Two imprisoned men form a bond over several years, finding solace and eventual redemption through acts of common decency.",
      casting: "Starring: Tim Robbins, Morgan Freeman, Bob Gunton",
    },
    {
      id: "C7",
      images: "/photo/img29.jpg",
      title: "Avatar",
      information: `2${"h"} 42${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 2009,
      genre: "Action",
      describ:
        "A paraplegic marine is dispatched to the moon Pandora on a unique mission and becomes torn between following orders and protecting an alien civilization.",
      casting: "Starring: Sam Worthington, Zoe Saldana, Sigourney Weaver",
    },
    {
      id: "C8",
      images: "/photo/img30.jpg",
      title: "Forrest Gump",
      information: `2${"h"} 22${"m"}`,
      agee: `${"PG-13"} ${"13+"}`,
      sal: 1994,
      genre: "Drama",
      describ:
        "The life journey of a man with a low IQ who witnesses and unwittingly influences several defining historical events in the 20th century USA.",
      casting: "Starring: Tom Hanks, Robin Wright, Gary Sinise",
    },
    {
      id: "C9",
      images: "/photo/img31.jpg",
      title: "The Matrix",
      information: `2${"h"} 16${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1999,
      genre: "Sci-Fi",
      describ:
        "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      casting: "Starring: Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    },
    {
      id: "C10",
      images: "/photo/img32.jpg",
      title: "Pulp Fiction",
      information: `2${"h"} 34${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1994,
      genre: "Crime",
      describ:
        "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      casting: "Starring: John Travolta, Uma Thurman, Samuel L. Jackson",
    },
    {
      id: "C11",
      images: "/photo/img33.jpg",
      title: "The Godfather",
      information: `2${"h"} 55${"m"}`,
      agee: `${"R"} ${"17+"}`,
      sal: 1972,
      genre: "Crime",
      describ:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      casting: "Starring: Marlon Brando, Al Pacino, James Caan",
    },
  ],
};

export const featuredMovies = [movieCategory1, movieCategory2, movieCategory3];
